version: '3.8'
services:
  website:
    build: '.'
    ports:
      - 8080:3000/tcp
    env_file:
      - '.env'
    environment:
      - DATABASE_CREDENTAILS="mysql://sog:sog@db/sog"
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      - MYSQL_USER=sog
      - MYSQL_PASSWORD=sog
      - MYSQL_ROOT_PASSWORD=sog
      - MYSQL_DATABASE=sog
    volumes:
      - db_data:/var/lib/mysql

  admin:
    image: phpmyadmin
    ports:
      - 8081:80/tcp
    depends_on:
      - db
